# Demonstration of relational algebra operations using `realed`

In [1]:
from realed import Relation

r1 = Relation("../data/palmerpenguins.csv")
r2 = Relation("../data/palmerislands.csv")

In [2]:
r1.naturaljoin(r2).project(["species", "island", "expedition"])

       species     island                              expedition
0       Adelie  Torgersen    Falkland Islands Dependencies Survey
20      Adelie     Biscoe               Southern Ocean Expedition
30      Adelie      Dream  British Naval Hydrographic Survey Unit
152     Gentoo     Biscoe               Southern Ocean Expedition
276  Chinstrap      Dream  British Naval Hydrographic Survey Unit

In [3]:
r1

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,6,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007
6,7,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007
7,8,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007
8,9,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007
9,10,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007
10,11,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,2007
11,12,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,2007
12,13,Adelie,Torgersen,41.1,17.6,182.0,3200.0,female,2007
13,14,Adelie,Torgersen,38.6,21.2,191.0,3800.0,male,2007
14,15,Adelie,Torgersen,34.6,21.1,198.0,4400.0,male,2007
15,16,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007
16,17,Adelie,Torgersen,38.7,19.0,195.0,3450.0,female,2007
17,18,Adelie,Torgersen,42.5,20.7,197.0,4500.0,male,2007
18,19,Adelie,Torgersen,34.4,18.4,184.0,3325.0,female,2007
19,20,Adelie,Torgersen,46.0,21.5,194.0,4200.0,male,2007
20,21,Adelie,Biscoe,37.8,18.3,174.0,3400.0,female,2007
21,22,Adelie,Biscoe,37.7,18.7,180.0,3600.0,male,2007
22,23,Adelie,Biscoe,35.9,19.2,189.0,3800.0,female,2007
23,24,Adelie,Biscoe,38.2,18.1,185.0,3950.0,male,2007
24,25,Adelie,Biscoe,38.8,17.2,180.0,3800.0,male,2007
25,26,Adelie,Biscoe,35.3,18.9,187.0,3800.0,female,2007
26,27,Adelie,Biscoe,40.6,18.6,183.0,3550.0,male,2007
27,28,Adelie,Biscoe,40.5,17.9,187.0,3200.0,female,2007
28,29,Adelie,Biscoe,37.9,18.6,172.0,3150.0,female,2007
29,30,Adelie,Biscoe,40.5,18.9,180.0,3950.0,male,2007
30,31,Adelie,Dream,39.5,16.7,178.0,3250.0,female,2007
31,32,Adelie,Dream,37.2,18.1,178.0,3900.0,male,2007
32,33,Adelie,Dream,39.5,17.8,188.0,3300.0,female,2007
33,34,Adelie,Dream,40.9,18.9,184.0,3900.0,male,2007
34,35,Adelie,Dream,36.4,17.0,195.0,3325.0,female,2007
35,36,Adelie,Dream,39.2,21.1,196.0,4150.0,male,2007
36,37,Adelie,Dream,38.8,20.0,190.0,3950.0,male,2007
37,38,Adelie,Dream,42.2,18.5,180.0,3550.0,female,2007
38,39,Adelie,Dream,37.6,19.3,181.0,3300.0,female,2007
39,40,Adelie,Dream,39.8,19.1,184.0,4650.0,male,2007
40,41,Adelie,Dream,36.5,18.0,182.0,3150.0,female,2007
41,42,Adelie,Dream,40.8,18.4,195.0,3900.0,male,2007
42,43,Adelie,Dream,36.0,18.5,186.0,3100.0,female,2007
43,44,Adelie,Dream,44.1,19.7,196.0,4400.0,male,2007
44,45,Adelie,Dream,37.0,16.9,185.0,3000.0,female,2007
45,46,Adelie,Dream,39.6,18.8,190.0,4600.0,male,2007
46,47,Adelie,Dream,41.1,19.0,182.0,3425.0,male,2007
47,48,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN,2007
48,49,Adelie,Dream,36.0,17.9,190.0,3450.0,female,2007
49,50,Adelie,Dream,42.3,21.2,191.0,4150.0,male,2007
50,51,Adelie,Biscoe,39.6,17.7,186.0,3500.0,female,2008
51,52,Adelie,Biscoe,40.1,18.9,188.0,4300.0,male,2008
52,53,Adelie,Biscoe,35.0,17.9,190.0,3450.0,female,2008
53,54,Adelie,Biscoe,42.0,19.5,200.0,4050.0,male,2008
54,55,Adelie,Biscoe,34.5,18.1,187.0,2900.0,female,2008
55,56,Adelie,Biscoe,41.4,18.6,191.0,3700.0,male,2008
56,57,Adelie,Biscoe,39.0,17.5,186.0,3550.0,female,2008
57,58,Adelie,Biscoe,40.6,18.8,193.0,3800.0,male,2008
58,59,Adelie,Biscoe,36.5,16.6,181.0,2850.0,female,2008
59,60,Adelie,Biscoe,37.6,19.1,194.0,3750.0,male,2008
60,61,Adelie,Biscoe,35.7,16.9,185.0,3150.0,female,2008
61,62,Adelie,Biscoe,41.3,21.1,195.0,4400.0,male,2008
62,63,Adelie,Biscoe,37.6,17.0,185.0,3600.0,female,2008
63,64,Adelie,Biscoe,41.1,18.2,192.0,4050.0,male,2008
64,65,Adelie,Biscoe,36.4,17.1,184.0,2850.0,female,2008
65,66,Adelie,Biscoe,41.6,18.0,192.0,3950.0,male,2008
66,67,Adelie,Biscoe,35.5,16.2,195.0,3350.0,female,2008
67,68,Adelie,Biscoe,41.1,19.1,188.0,4100.0,male,2008
68,69,Adelie,Torgersen,35.9,16.6,190.0,3050.0,female,2008
69,70,Adelie,Torgersen,41.8,19.4,198.0,4450.0,male,2008
70,71,Adelie,Torgersen,33.5,19.0,190.0,3600.0,female,2008
71,72,Adelie,Torgersen,39.7,18.4,190.0,3900.0,male,2008
72,73,Adelie,Torgersen,39.6,17.2,196.0,3550.0,female,2008
73,74,Adelie,Torgersen,45.8,18.9,197.0,4150.0,male,2008
74,75,Adelie,Torgersen,35.5,17.5,190.0,3700.0,female,2008
75,76,Adelie,Torgersen,42.8,18.5,195.0,4250.0,male,2008
76,77,Adelie,Torgersen,40.9,16.8,191.0,3700.0,female,2008
77,78,Adelie,Torgersen,37.2,19.4,184.0,3900.0,male,2008
78,79,Adelie,Torgersen,36.2,16.1,187.0,3550.0,female,2008
79,80,Adelie,Torgersen,42.1,19.1,195.0,4000.0,male,2008
80,81,Adelie,Torgersen,34.6,17.2,189.0,3200.0,female,2008
81,82,Adelie,Torgersen,42.9,17.6,196.0,4700.0,male,2008
82,83,Adelie,Torgersen,36.7,18.8,187.0,3800.0,female,2008
83,84,Adelie,Torgersen,35.1,19.4,193.0,4200.0,male,2008
84,85,Adelie,Dream,37.3,17.8,191.0,3350.0,female,2008
85,86,Adelie,Dream,41.3,20.3,194.0,3550.0,male,2008
86,87,Adelie,Dream,36.3,19.5,190.0,3800.0,male,2008
87,88,Adelie,Dream,36.9,18.6,189.0,3500.0,female,2008
88,89,Adelie,Dream,38.3,19.2,189.0,3950.0,male,2008
89,90,Adelie,Dream,38.9,18.8,190.0,3600.0,female,2008
90,91,Adelie,Dream,35.7,18.0,202.0,3550.0,female,2008
91,92,Adelie,Dream,41.1,18.1,205.0,4300.0,male,2008
92,93,Adelie,Dream,34.0,17.1,185.0,3400.0,female,2008
93,94,Adelie,Dream,39.6,18.1,186.0,4450.0,male,2008
94,95,Adelie,Dream,36.2,17.3,187.0,3300.0,female,2008
95,96,Adelie,Dream,40.8,18.9,208.0,4300.0,male,2008
96,97,Adelie,Dream,38.1,18.6,190.0,3700.0,female,2008
97,98,Adelie,Dream,40.3,18.5,196.0,4350.0,male,2008
98,99,Adelie,Dream,33.1,16.1,178.0,2900.0,female,2008
99,100,Adelie,Dream,43.2,18.5,192.0,4100.0,male,2008
100,101,Adelie,Biscoe,35.0,17.9,192.0,3725.0,female,2009
101,102,Adelie,Biscoe,41.0,20.0,203.0,4725.0,male,2009
102,103,Adelie,Biscoe,37.7,16.0,183.0,3075.0,female,2009
103,104,Adelie,Biscoe,37.8,20.0,190.0,4250.0,male,2009
104,105,Adelie,Biscoe,37.9,18.6,193.0,2925.0,female,2009
105,106,Adelie,Biscoe,39.7,18.9,184.0,3550.0,male,2009
106,107,Adelie,Biscoe,38.6,17.2,199.0,3750.0,female,2009
107,108,Adelie,Biscoe,38.2,20.0,190.0,3900.0,male,2009
108,109,Adelie,Biscoe,38.1,17.0,181.0,3175.0,female,2009
109,110,Adelie,Biscoe,43.2,19.0,197.0,4775.0,male,2009
110,111,Adelie,Biscoe,38.1,16.5,198.0,3825.0,female,2009
111,112,Adelie,Biscoe,45.6,20.3,191.0,4600.0,male,2009
112,113,Adelie,Biscoe,39.7,17.7,193.0,3200.0,female,2009
113,114,Adelie,Biscoe,42.2,19.5,197.0,4275.0,male,2009
114,115,Adelie,Biscoe,39.6,20.7,191.0,3900.0,female,2009
115,116,Adelie,Biscoe,42.7,18.3,196.0,4075.0,male,2009
116,117,Adelie,Torgersen,38.6,17.0,188.0,2900.0,female,2009
117,118,Adelie,Torgersen,37.3,20.5,199.0,3775.0,male,2009
118,119,Adelie,Torgersen,35.7,17.0,189.0,3350.0,female,2009
119,120,Adelie,Torgersen,41.1,18.6,189.0,3325.0,male,2009
120,121,Adelie,Torgersen,36.2,17.2,187.0,3150.0,female,2009
121,122,Adelie,Torgersen,37.7,19.8,198.0,3500.0,male,2009
122,123,Adelie,Torgersen,40.2,17.0,176.0,3450.0,female,2009
123,124,Adelie,Torgersen,41.4,18.5,202.0,3875.0,male,2009
124,125,Adelie,Torgersen,35.2,15.9,186.0,3050.0,female,2009
125,126,Adelie,Torgersen,40.6,19.0,199.0,4000.0,male,2009
126,127,Adelie,Torgersen,38.8,17.6,191.0,3275.0,female,2009
127,128,Adelie,Torgersen,41.5,18.3,195.0,4300.0,male,2009
128,129,Adelie,Torgersen,39.0,17.1,191.0,3050.0,female,2009
129,130,Adelie,Torgersen,44.1,18.0,210.0,4000.0,male,2009
130,131,Adelie,Torgersen,38.5,17.9,190.0,3325.0,female,2009
131,132,Adelie,Torgersen,43.1,19.2,197.0,3500.0,male,2009
132,133,Adelie,Dream,36.8,18.5,193.0,3500.0,female,2009
133,134,Adelie,Dream,37.5,18.5,199.0,4475.0,male,2009
134,135,Adelie,Dream,38.1,17.6,187.0,3425.0,female,2009
135,136,Adelie,Dream,41.1,17.5,190.0,3900.0,male,2009
136,137,Adelie,Dream,35.6,17.5,191.0,3175.0,female,2009
137,138,Adelie,Dream,40.2,20.1,200.0,3975.0,male,2009
138,139,Adelie,Dream,37.0,16.5,185.0,3400.0,female,2009
139,140,Adelie,Dream,39.7,17.9,193.0,4250.0,male,2009
140,141,Adelie,Dream,40.2,17.1,193.0,3400.0,female,2009
141,142,Adelie,Dream,40.6,17.2,187.0,3475.0,male,2009
142,143,Adelie,Dream,32.1,15.5,188.0,3050.0,female,2009
143,144,Adelie,Dream,40.7,17.0,190.0,3725.0,male,2009
144,145,Adelie,Dream,37.3,16.8,192.0,3000.0,female,2009
145,146,Adelie,Dream,39.0,18.7,185.0,3650.0,male,2009
146,147,Adelie,Dream,39.2,18.6,190.0,4250.0,male,2009
147,148,Adelie,Dream,36.6,18.4,184.0,3475.0,female,2009
148,149,Adelie,Dream,36.0,17.8,195.0,3450.0,female,2009
149,150,Adelie,Dream,37.8,18.1,193.0,3750.0,male,2009
150,151,Adelie,Dream,36.0,17.1,187.0,3700.0,female,2009
151,152,Adelie,Dream,41.5,18.5,201.0,4000.0,male,2009
152,153,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,female,2007
153,154,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
154,155,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,female,2007
155,156,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,157,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
157,158,Gentoo,Biscoe,46.5,13.5,210.0,4550.0,female,2007
158,159,Gentoo,Biscoe,45.4,14.6,211.0,4800.0,female,2007
159,160,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,male,2007
160,161,Gentoo,Biscoe,43.3,13.4,209.0,4400.0,female,2007
161,162,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,male,2007
162,163,Gentoo,Biscoe,40.9,13.7,214.0,4650.0,female,2007
163,164,Gentoo,Biscoe,49.0,16.1,216.0,5550.0,male,2007
164,165,Gentoo,Biscoe,45.5,13.7,214.0,4650.0,female,2007
165,166,Gentoo,Biscoe,48.4,14.6,213.0,5850.0,male,2007
166,167,Gentoo,Biscoe,45.8,14.6,210.0,4200.0,female,2007
167,168,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,male,2007
168,169,Gentoo,Biscoe,42.0,13.5,210.0,4150.0,female,2007
169,170,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007
170,171,Gentoo,Biscoe,46.2,14.5,209.0,4800.0,female,2007
171,172,Gentoo,Biscoe,48.7,15.1,222.0,5350.0,male,2007
172,173,Gentoo,Biscoe,50.2,14.3,218.0,5700.0,male,2007
173,174,Gentoo,Biscoe,45.1,14.5,215.0,5000.0,female,2007
174,175,Gentoo,Biscoe,46.5,14.5,213.0,4400.0,female,2007
175,176,Gentoo,Biscoe,46.3,15.8,215.0,5050.0,male,2007
176,177,Gentoo,Biscoe,42.9,13.1,215.0,5000.0,female,2007
177,178,Gentoo,Biscoe,46.1,15.1,215.0,5100.0,male,2007
178,179,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN,2007
179,180,Gentoo,Biscoe,47.8,15.0,215.0,5650.0,male,2007
180,181,Gentoo,Biscoe,48.2,14.3,210.0,4600.0,female,2007
181,182,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,male,2007
182,183,Gentoo,Biscoe,47.3,15.3,222.0,5250.0,male,2007
183,184,Gentoo,Biscoe,42.8,14.2,209.0,4700.0,female,2007
184,185,Gentoo,Biscoe,45.1,14.5,207.0,5050.0,female,2007
185,186,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007
186,187,Gentoo,Biscoe,49.1,14.8,220.0,5150.0,female,2008
187,188,Gentoo,Biscoe,48.4,16.3,220.0,5400.0,male,2008
188,189,Gentoo,Biscoe,42.6,13.7,213.0,4950.0,female,2008
189,190,Gentoo,Biscoe,44.4,17.3,219.0,5250.0,male,2008
190,191,Gentoo,Biscoe,44.0,13.6,208.0,4350.0,female,2008
191,192,Gentoo,Biscoe,48.7,15.7,208.0,5350.0,male,2008
192,193,Gentoo,Biscoe,42.7,13.7,208.0,3950.0,female,2008
193,194,Gentoo,Biscoe,49.6,16.0,225.0,5700.0,male,2008
194,195,Gentoo,Biscoe,45.3,13.7,210.0,4300.0,female,2008
195,196,Gentoo,Biscoe,49.6,15.0,216.0,4750.0,male,2008
196,197,Gentoo,Biscoe,50.5,15.9,222.0,5550.0,male,2008
197,198,Gentoo,Biscoe,43.6,13.9,217.0,4900.0,female,2008
198,199,Gentoo,Biscoe,45.5,13.9,210.0,4200.0,female,2008
199,200,Gentoo,Biscoe,50.5,15.9,225.0,5400.0,male,2008
200,201,Gentoo,Biscoe,44.9,13.3,213.0,5100.0,female,2008
201,202,Gentoo,Biscoe,45.2,15.8,215.0,5300.0,male,2008
202,203,Gentoo,Biscoe,46.6,14.2,210.0,4850.0,female,2008
203,204,Gentoo,Biscoe,48.5,14.1,220.0,5300.0,male,2008
204,205,Gentoo,Biscoe,45.1,14.4,210.0,4400.0,female,2008
205,206,Gentoo,Biscoe,50.1,15.0,225.0,5000.0,male,2008
206,207,Gentoo,Biscoe,46.5,14.4,217.0,4900.0,female,2008
207,208,Gentoo,Biscoe,45.0,15.4,220.0,5050.0,male,2008
208,209,Gentoo,Biscoe,43.8,13.9,208.0,4300.0,female,2008
209,210,Gentoo,Biscoe,45.5,15.0,220.0,5000.0,male,2008
210,211,Gentoo,Biscoe,43.2,14.5,208.0,4450.0,female,2008
211,212,Gentoo,Biscoe,50.4,15.3,224.0,5550.0,male,2008
212,213,Gentoo,Biscoe,45.3,13.8,208.0,4200.0,female,2008
213,214,Gentoo,Biscoe,46.2,14.9,221.0,5300.0,male,2008
214,215,Gentoo,Biscoe,45.7,13.9,214.0,4400.0,female,2008
215,216,Gentoo,Biscoe,54.3,15.7,231.0,5650.0,male,2008
216,217,Gentoo,Biscoe,45.8,14.2,219.0,4700.0,female,2008
217,218,Gentoo,Biscoe,49.8,16.8,230.0,5700.0,male,2008
218,219,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN,2008
219,220,Gentoo,Biscoe,49.5,16.2,229.0,5800.0,male,2008
220,221,Gentoo,Biscoe,43.5,14.2,220.0,4700.0,female,2008
221,222,Gentoo,Biscoe,50.7,15.0,223.0,5550.0,male,2008
222,223,Gentoo,Biscoe,47.7,15.0,216.0,4750.0,female,2008
223,224,Gentoo,Biscoe,46.4,15.6,221.0,5000.0,male,2008
224,225,Gentoo,Biscoe,48.2,15.6,221.0,5100.0,male,2008
225,226,Gentoo,Biscoe,46.5,14.8,217.0,5200.0,female,2008
226,227,Gentoo,Biscoe,46.4,15.0,216.0,4700.0,female,2008
227,228,Gentoo,Biscoe,48.6,16.0,230.0,5800.0,male,2008
228,229,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,female,2008
229,230,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008
230,231,Gentoo,Biscoe,45.2,13.8,215.0,4750.0,female,2008
231,232,Gentoo,Biscoe,45.2,16.4,223.0,5950.0,male,2008
232,233,Gentoo,Biscoe,49.1,14.5,212.0,4625.0,female,2009
233,234,Gentoo,Biscoe,52.5,15.6,221.0,5450.0,male,2009
234,235,Gentoo,Biscoe,47.4,14.6,212.0,4725.0,female,2009
235,236,Gentoo,Biscoe,50.0,15.9,224.0,5350.0,male,2009
236,237,Gentoo,Biscoe,44.9,13.8,212.0,4750.0,female,2009
237,238,Gentoo,Biscoe,50.8,17.3,228.0,5600.0,male,2009
238,239,Gentoo,Biscoe,43.4,14.4,218.0,4600.0,female,2009
239,240,Gentoo,Biscoe,51.3,14.2,218.0,5300.0,male,2009
240,241,Gentoo,Biscoe,47.5,14.0,212.0,4875.0,female,2009
241,242,Gentoo,Biscoe,52.1,17.0,230.0,5550.0,male,2009
242,243,Gentoo,Biscoe,47.5,15.0,218.0,4950.0,female,2009
243,244,Gentoo,Biscoe,52.2,17.1,228.0,5400.0,male,2009
244,245,Gentoo,Biscoe,45.5,14.5,212.0,4750.0,female,2009
245,246,Gentoo,Biscoe,49.5,16.1,224.0,5650.0,male,2009
246,247,Gentoo,Biscoe,44.5,14.7,214.0,4850.0,female,2009
247,248,Gentoo,Biscoe,50.8,15.7,226.0,5200.0,male,2009
248,249,Gentoo,Biscoe,49.4,15.8,216.0,4925.0,male,2009
249,250,Gentoo,Biscoe,46.9,14.6,222.0,4875.0,female,2009
250,251,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,female,2009
251,252,Gentoo,Biscoe,51.1,16.5,225.0,5250.0,male,2009
252,253,Gentoo,Biscoe,48.5,15.0,219.0,4850.0,female,2009
253,254,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,male,2009
254,255,Gentoo,Biscoe,47.2,15.5,215.0,4975.0,female,2009
255,256,Gentoo,Biscoe,49.1,15.0,228.0,5500.0,male,2009
256,257,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN,2009
257,258,Gentoo,Biscoe,46.8,16.1,215.0,5500.0,male,2009
258,259,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,female,2009
259,260,Gentoo,Biscoe,53.4,15.8,219.0,5500.0,male,2009
260,261,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,female,2009
261,262,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,male,2009
262,263,Gentoo,Biscoe,50.5,15.2,216.0,5000.0,female,2009
263,264,Gentoo,Biscoe,49.8,15.9,229.0,5950.0,male,2009
264,265,Gentoo,Biscoe,43.5,15.2,213.0,4650.0,female,2009
265,266,Gentoo,Biscoe,51.5,16.3,230.0,5500.0,male,2009
266,267,Gentoo,Biscoe,46.2,14.1,217.0,4375.0,female,2009
267,268,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009
268,269,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN,2009
269,270,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
270,271,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,female,2009
271,272,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009
272,273,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,female,2009
273,274,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,275,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,276,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009
276,277,Chinstrap,Dream,46.5,17.9,192.0,3500.0,female,2007
277,278,Chinstrap,Dream,50.0,19.5,196.0,3900.0,male,2007
278,279,Chinstrap,Dream,51.3,19.2,193.0,3650.0,male,2007
279,280,Chinstrap,Dream,45.4,18.7,188.0,3525.0,female,2007
280,281,Chinstrap,Dream,52.7,19.8,197.0,3725.0,male,2007
281,282,Chinstrap,Dream,45.2,17.8,198.0,3950.0,female,2007
282,283,Chinstrap,Dream,46.1,18.2,178.0,3250.0,female,2007
283,284,Chinstrap,Dream,51.3,18.2,197.0,3750.0,male,2007
284,285,Chinstrap,Dream,46.0,18.9,195.0,4150.0,female,2007
285,286,Chinstrap,Dream,51.3,19.9,198.0,3700.0,male,2007
286,287,Chinstrap,Dream,46.6,17.8,193.0,3800.0,female,2007
287,288,Chinstrap,Dream,51.7,20.3,194.0,3775.0,male,2007
288,289,Chinstrap,Dream,47.0,17.3,185.0,3700.0,female,2007
289,290,Chinstrap,Dream,52.0,18.1,201.0,4050.0,male,2007
290,291,Chinstrap,Dream,45.9,17.1,190.0,3575.0,female,2007
291,292,Chinstrap,Dream,50.5,19.6,201.0,4050.0,male,2007
292,293,Chinstrap,Dream,50.3,20.0,197.0,3300.0,male,2007
293,294,Chinstrap,Dream,58.0,17.8,181.0,3700.0,female,2007
294,295,Chinstrap,Dream,46.4,18.6,190.0,3450.0,female,2007
295,296,Chinstrap,Dream,49.2,18.2,195.0,4400.0,male,2007
296,297,Chinstrap,Dream,42.4,17.3,181.0,3600.0,female,2007
297,298,Chinstrap,Dream,48.5,17.5,191.0,3400.0,male,2007
298,299,Chinstrap,Dream,43.2,16.6,187.0,2900.0,female,2007
299,300,Chinstrap,Dream,50.6,19.4,193.0,3800.0,male,2007
300,301,Chinstrap,Dream,46.7,17.9,195.0,3300.0,female,2007
301,302,Chinstrap,Dream,52.0,19.0,197.0,4150.0,male,2007
302,303,Chinstrap,Dream,50.5,18.4,200.0,3400.0,female,2008
303,304,Chinstrap,Dream,49.5,19.0,200.0,3800.0,male,2008
304,305,Chinstrap,Dream,46.4,17.8,191.0,3700.0,female,2008
305,306,Chinstrap,Dream,52.8,20.0,205.0,4550.0,male,2008
306,307,Chinstrap,Dream,40.9,16.6,187.0,3200.0,female,2008
307,308,Chinstrap,Dream,54.2,20.8,201.0,4300.0,male,2008
308,309,Chinstrap,Dream,42.5,16.7,187.0,3350.0,female,2008
309,310,Chinstrap,Dream,51.0,18.8,203.0,4100.0,male,2008
310,311,Chinstrap,Dream,49.7,18.6,195.0,3600.0,male,2008
311,312,Chinstrap,Dream,47.5,16.8,199.0,3900.0,female,2008
312,313,Chinstrap,Dream,47.6,18.3,195.0,3850.0,female,2008
313,314,Chinstrap,Dream,52.0,20.7,210.0,4800.0,male,2008
314,315,Chinstrap,Dream,46.9,16.6,192.0,2700.0,female,2008
315,316,Chinstrap,Dream,53.5,19.9,205.0,4500.0,male,2008
316,317,Chinstrap,Dream,49.0,19.5,210.0,3950.0,male,2008
317,318,Chinstrap,Dream,46.2,17.5,187.0,3650.0,female,2008
318,319,Chinstrap,Dream,50.9,19.1,196.0,3550.0,male,2008
319,320,Chinstrap,Dream,45.5,17.0,196.0,3500.0,female,2008
320,321,Chinstrap,Dream,50.9,17.9,196.0,3675.0,female,2009
321,322,Chinstrap,Dream,50.8,18.5,201.0,4450.0,male,2009
322,323,Chinstrap,Dream,50.1,17.9,190.0,3400.0,female,2009
323,324,Chinstrap,Dream,49.0,19.6,212.0,4300.0,male,2009
324,325,Chinstrap,Dream,51.5,18.7,187.0,3250.0,male,2009
325,326,Chinstrap,Dream,49.8,17.3,198.0,3675.0,female,2009
326,327,Chinstrap,Dream,48.1,16.4,199.0,3325.0,female,2009
327,328,Chinstrap,Dream,51.4,19.0,201.0,3950.0,male,2009
328,329,Chinstrap,Dream,45.7,17.3,193.0,3600.0,female,2009
329,330,Chinstrap,Dream,50.7,19.7,203.0,4050.0,male,2009
330,331,Chinstrap,Dream,42.5,17.3,187.0,3350.0,female,2009
331,332,Chinstrap,Dream,52.2,18.8,197.0,3450.0,male,2009
332,333,Chinstrap,Dream,45.2,16.6,191.0,3250.0,female,2009
333,334,Chinstrap,Dream,49.3,19.9,203.0,4050.0,male,2009
334,335,Chinstrap,Dream,50.2,18.8,202.0,3800.0,male,2009
335,336,Chinstrap,Dream,45.6,19.4,194.0,3525.0,female,2009
336,337,Chinstrap,Dream,51.9,19.5,206.0,3950.0,male,2009
337,338,Chinstrap,Dream,46.8,16.5,189.0,3650.0,female,2009
338,339,Chinstrap,Dream,45.7,17.0,195.0,3650.0,female,2009
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009