# Demonstration of relational algebra operations using `realed`

In [1]:
from realed import Relation

r1 = Relation("../data/palmerpenguins.csv")
r2 = Relation("../data/palmerislands.csv")

In [2]:
r1.naturaljoin(r2).project(["species", "island", "expedition"])

       species     island                              expedition
0       Adelie  Torgersen    Falkland Islands Dependencies Survey
20      Adelie     Biscoe               Southern Ocean Expedition
30      Adelie      Dream  British Naval Hydrographic Survey Unit
152     Gentoo     Biscoe               Southern Ocean Expedition
276  Chinstrap      Dream  British Naval Hydrographic Survey Unit

In [3]:
r1

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009